spring:
  application:
    name: bancoDeSangue
  datasource:
    url: jdbc:postgresql://localhost:5432/banco-de-sangue
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver


  flyway:
    baseline-on-migrate: true
    enabled: true
    locations: classpath:db/migration

api:
  security:
      token:
        secret: ${JWT_SECRET:my-secret-key}
logging:
      level:
        org.springframework.security: DEBUG
        org.h2: DEBUG