spring:
  application:
    name: bancoDeSangue
  datasource:
    url: jdbc:postgresql://localhost:5432/banco-de-sangue
    username: postgres
    password: sagi
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true
    enabled: true
    locations: classpath:db/migration

api:
  security:
    token:
      secret: GJMdO3DfUsG5eY3+t5DgUj0PLbKH2Gf6X3z1yTb9w9c=
      issuer: http://localhost:8080
      audience: auth-api

logging:
  level:
    org.springframework.security: DEBUG
    org.h2: DEBUG
